logo: "/images/avatar.jpg?size=10% auto" # your photo (or logo) here

title: Shubham Kumar Goswami # your name (or website title) here
#avatar: "/images/avatar.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD at <a href="http://www.cds.iisc.ac.in/">Department of Computational and Data Sciences</a>  
  <br>
  <a href="https://www.iisc.ac.in/">Indian Institute of Science, Bangalore</a>  
  <br><br>
  <a href="https://github.com/gshubhamk/">View My Github Profile</a>

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
