title: Shubham Kumar Goswami # your name (or website title) here
avatar: /images/avatar.jpg # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD at <a href="https://www.cds.iisc.ac.in/">Department of Computational and Data Sciences</a>  
  <br><br>
  <a href="https://www.iisc.ac.in/">Indian Institute of Science, Bangalore</a>  
  <br><br>
  <a href="https://www.linkedin.com/in/shubham-kumar-goswami-7a4a8795/">View My LinkedIn Profile</a>

theme: jekyll-theme-dinky
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
